services:
  - type: web
    name: leetcode-anxiety-index
    runtime: python
    buildCommand: pip install -r requirements.txt && python database/db.py && python data_collection/google_trends.py && python data_collection/stock_data.py && python indicator/lai_calculator.py
    startCommand: gunicorn dashboard.app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
    plan: free
